name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.ACCESS_TOKEN }}
        issue-message: 'Thanks for helping Jalgorithm enhance.❤'
        pr-message: 'Congrats!!🖐🎉✨You had your first contribution to Jalgorithm and now you are one of us😍'
